-- ALTER TABLE "Histories"
-- ADD COLUMN title VARCHAR(255) NOT NULL,
-- ADD COLUMN "playedAt" TIMESTAMP NOT NULL,
-- ADD COLUMN url VARCHAR(255) NOT NULL;


CREATE TABLE "Blogs" (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "UserId" INTEGER REFERENCES "Users"(id) ON DELETE SET NULL
);