version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/app
      - server_node_modules:/usr/src/app/node_modules

  client:
    build:
      context: ./client/videos-app
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    volumes:
      - ./client/videos-app:/usr/src/app
      - client_node_modules:/usr/src/app/node_modules

volumes:
  db_data:
  server_node_modules:
  client_node_modules: